In [6]:
import numpy as np

Vectorized Operations: operates on entire arrays at once without explicit Python for loops

In [ ]:
a = [1,2,3]
b=[4,5,6]
res = [x + y for x, y in zip(a, b)]
mul = [x*y for x,y in zip(a,b)]
print(res)

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b); print(a/b)
print(a@b)
print(a*b); print(a-b)

Broadcasting: perform arithmetic operations on arrays of different shapes without copying data.

Broadcasting Rule: Two dimensions are compatible when:

- They are equal, OR
- One of them is 1.

In [ ]:
# Add a 1D bias vector (length 3) to every row of a 2D matrix (4x3)

matrix = [[1, 2, 3], [4, 5, 6], 
          [7, 8, 9], [10, 11, 12]]
bias = [10, 20, 30]

out = []

for row in matrix:
    out.append([r+b for r,b in zip(row, bias)])

print(out)

In [ ]:
matrix = np.arange(1,13).reshape(4,3)
bias = np.array([10,20,30])

out = matrix+bias
print(out)

Advanced Indexing & Slicing: Index directly using integer arrays or boolean masks to filter and modify data without iteration.

In [ ]:
# Select positive numbers and set negative ones to 0

data = [-2, 5, 3, -8, 10, -1]

filtered = []
for i,x in enumerate(data):
    if x>0:
        filtered.append(x)
    elif x<0:
        data[i]=0

print(data)
print(filtered)

In [ ]:
data=np.array([-2,5,3,-8,10,-1])

positive=data[data>0]  #new array positive with only data grater than 0

data[data<0]=0 #in-place change data

print(positive, data)

In [ ]:
data = np.array([-2,5,3,-8,10,-1])

data1 = np.maximum(data, 0, out=data) #In-place max clipping

data2 = np.clip(data, a_min=0, a_max=None) #Clip lower bound 
print(data1, data2)

Einstein Summation: np.einsum

np.einsum gives a compact notation to perform matrix multiplications, transpositions, trace calculations, and reductions using index labels.

Example A: Matrix MultiplicationFormula: $C_{ij} = \sum_k A_{ik} B_{kj}$

Notation: 'ik,kj->ij'

In [ ]:
A = np.random.randn(3, 4)
print(A)
B = np.random.randn(4, 5)
print(B)
# Standard: C = A @ B
C = np.einsum("ik,kj->ij", A, B)  # Output shape: (3, 5)
print(C)

In [ ]:
a = np.arange(12).reshape(3, 4)
print(a)
b = np.array([1, 2, 3])
print(b)

print(b[:,None])
#a + b          # predict: works or fails?
a + b[:, None] # predict: works or fails? what shape?

In [ ]:
a = np.arange(10)
b = a[2:5]
b[0] = 99
print(a)      # did a change?

c = a[a > 3]
c[0] = 999
print(a)      # did a change now?

In [5]:
data = [1,3,5,7,9]
result = []
for x in data:
    result.append(x ** 2 + 2 * x + 1)
print(data)

[1, 3, 5, 7, 9]


In [ ]:
data = np.array([1,3,5,7,9])
data1=np.arange(1,10,2)
data2=np.arange(1,10,2).reshape(1,5)
data3=np.arange(1,10,2).reshape(5,1)
result = data ** 2 + 2 * data + 1
print(result)
print(data1)
print(data2)
print(data3)
print(data2.reshape(-1)) 
# data.reshape(-1)   # recommended 
# data.ravel()       # also common
# data.flatten()     # creates a copy

[  4  16  36  64 100]
[1 3 5 7 9]
[[1 3 5 7 9]]
[[1]
 [3]
 [5]
 [7]
 [9]]
[1 3 5 7 9]


In [22]:
prices = np.array([100, 50, 200, 75, 300])
# Replace any price > 150 with 150 (cap), else keep original
capped = np.where(prices > 150, 150, prices)
print(capped)

[100  50 150  75 150]


In [24]:
m = np.arange(12).reshape(3, 4)
print(m)
print(m.sum(axis=0))   # shape? what does each value mean?
print(m.sum(axis=1))   # shape? what does each value mean?

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[ 6 22 38]


In [ ]:
import numpy as np
data = np.load("prices.npy")

# Normalize each row to zero mean, unit variance
mean=data.mean(axis=1, keepdims=True)
std=data.std(axis=1, keepdims=True)


FileNotFoundError: [Errno 2] No such file or directory: 'prices.npy'

: 