In [1]:
import numpy as np

Vectorized Operations: operates on entire arrays at once without explicit Python for loops

In [4]:
a = [1,2,3]; b=[4,5,6]
res = [x + y for x, y in zip(a, b)]
mul = [x*y for x,y in zip(a,b)]
print(res)
print(mul)

[5, 7, 9]
[4, 10, 18]


In [6]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a@b)
print(a*b)

[5 7 9]
32
[ 4 10 18]


Broadcasting: perform arithmetic operations on arrays of different shapes without copying data.

Broadcasting Rule: Two dimensions are compatible when:

- They are equal, OR
- One of them is 1.

In [7]:
# Add a 1D bias vector (length 3) to every row of a 2D matrix (4x3)

matrix = [[1, 2, 3], [4, 5, 6], 
          [7, 8, 9], [10, 11, 12]]
bias = [10, 20, 30]

out = []

for row in matrix:
    out.append([r+b for r,b in zip(row, bias)])

print(out)

[[11, 22, 33], [14, 25, 36], [17, 28, 39], [20, 31, 42]]


In [8]:
matrix = np.arange(1,13).reshape(4,3)
bias = np.array([10,20,30])

out = matrix+bias
print(out)

[[11 22 33]
 [14 25 36]
 [17 28 39]
 [20 31 42]]


Advanced Indexing & Slicing: Index directly using integer arrays or boolean masks to filter and modify data without iteration.

In [11]:
# Select positive numbers and set negative ones to 0

data = [-2, 5, 3, -8, 10, -1]

filtered = []
for i,x in enumerate(data):
    if x>0:
        filtered.append(x)
    elif x<0:
        data[i]=0

print(data)
print(filtered)

[0, 5, 3, 0, 10, 0]
[5, 3, 10]


In [12]:
data=np.array([-2,5,3,-8,10,-1])

positive=data[data>0]  #new array positive with only data grater than 0

data[data<0]=0 #in-place change data

print(positive, data)

[ 5  3 10] [ 0  5  3  0 10  0]


In [27]:
data = np.array([-2,5,3,-8,10,-1])

np.maximum(data, 0, out=data) #In-place max clipping

data2 = np.clip(data, a_min=0, a_max=None) #Clip lower bound 
print(data2)

[ 0  5  3  0 10  0]


Einstein Summation: np.einsum

np.einsum gives a compact notation to perform matrix multiplications, transpositions, trace calculations, and reductions using index labels.

Example A: Matrix MultiplicationFormula: $C_{ij} = \sum_k A_{ik} B_{kj}$

Notation: 'ik,kj->ij'

In [28]:
A = np.random.randn(3, 4)
print(A)
B = np.random.randn(4, 5)
print(B)
# Standard: C = A @ B
C = np.einsum("ik,kj->ij", A, B)  # Output shape: (3, 5)
print(C)

[[-1.9330851  -1.54660002  0.59033721 -1.8068433 ]
 [ 0.06164561 -1.48175699  0.46617185 -0.59314959]
 [ 0.93336266 -1.14893506 -1.47393129  0.18458121]]
[[ 0.67139943 -0.79009923 -1.18396705 -0.29680585 -1.03540683]
 [-0.2179445   1.71955885 -0.97790587  1.29378699  0.87367695]
 [-0.75089341  1.08344085 -0.10407041 -0.94567424  0.3928037 ]
 [-1.31952927  0.02051151  0.19582629 -2.05025122  0.06427651]]
[[ 0.98010302 -0.52960633  3.38587424  1.71899596  0.76604979]
 [ 0.79696249 -2.10377127  1.21136351 -1.16011573 -1.21341678]
 [ 1.74026822 -4.3062419   0.2080182  -0.74808371 -2.53730959]]


Changing dim using None

In [31]:
a = np.arange(12).reshape(3, 4)
print(a)
b = np.array([1, 2, 3])
print(b)
print(b.shape)
print(b[:,None])
#a + b          # predict: works or fails?
a + b[:, None] # predict: works or fails? what shape?

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[1 2 3]
(3,)
[[1]
 [2]
 [3]]


array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

Array slicing vs conditional
Slicing doesn't create a new array, its a view at same memory so any change on slice will affect the array as whole
Conditional creates/copies a new array at new mem location

In [27]:
a = np.arange(10)
print("a:",a)
b = a[2:5]
b[0] = 99
print("b:",b)
print("a:",a)      # did a change?


c = a[a > 3]
print("c:",c)
c[0] = 999
print("c:",c)
print("a:",a)      # did a change now?


a: [0 1 2 3 4 5 6 7 8 9]
b: [99  3  4]
a: [ 0  1 99  3  4  5  6  7  8  9]
c: [99  4  5  6  7  8  9]
c: [999   4   5   6   7   8   9]
a: [ 0  1 99  3  4  5  6  7  8  9]


In [5]:
data = [1,3,5,7,9]
result = []
for x in data:
    result.append(x ** 2 + 2 * x + 1)
print(data)

[1, 3, 5, 7, 9]


Arange(start, stop+1,step(default 1))

reshape(row, col), (-1->flatten it to 1D)

In [35]:
data = np.array([1,3,5,7,9])
data1=np.arange(1,10,2)
data2=np.arange(1,10,2).reshape(1,5)
data3=np.arange(1,10,2).reshape(5,1)
result = data ** 2 + 2 * data + 1
print(result.tolist())
print(data1)
print(data2)
print(data3)
print(data2.reshape(-1)) 
# data.reshape(-1)   # recommended 
# data.ravel()       # also common
# data.flatten()     # creates a copy

[4, 16, 36, 64, 100]
[1 3 5 7 9]
[[1 3 5 7 9]]
[[1]
 [3]
 [5]
 [7]
 [9]]
[1 3 5 7 9]


where(condition, true, false)

In [22]:
prices = np.array([100, 50, 200, 75, 300])
# Replace any price > 150 with 150 (cap), else keep original
capped = np.where(prices > 150, 150, prices)
print(capped)

[100  50 150  75 150]


In [ ]:
a = np.array([1, 5, 3, 8, 2])
b = np.array([4, 2, 6, 1, 9])

np.where(a > b, a, b)   # elementwise max: [4, 5, 6, 8, 9]

array([4, 5, 6, 8, 9])

Nested Where

In [ ]:
low  = np.array([2, 2, 2, 2, 2])
high = np.array([7, 7, 7, 7, 7])
data = np.array([-1, 3, 10, 5, 1])

np.where(data < low, low, np.where(data > high, high, data))
# → [2, 3, 7, 5, 2]

array([2, 3, 7, 5, 2])

In [ ]:
returns = np.array([0.02, -0.01, 0.05, -0.03, 0.0])

labels = np.where(returns > 0.03, 1,       # strong up
         np.where(returns < -0.02, -1,      # strong down
                  0))                        # neutral
# → [0, 0, 1, -1, 0]

array([ 0,  0,  1, -1,  0])

Sum, Mean, Std on array

Axis: 0= cols; 1=rows

In [24]:
m = np.arange(12).reshape(3, 4)
print(m)
print(m.sum(axis=0))   # shape? what does each value mean?
print(m.sum(axis=1))   # shape? what does each value mean?

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[ 6 22 38]


In [8]:
import numpy as np
data = np.load("practice_dataset.npy")
print("data", data)
# Normalize each row to zero mean, unit variance
mean=data.mean(axis=1, keepdims=True)
print("mean", mean)
std=data.std(axis=1, keepdims=True)
print("std",std)
normalized = (data - mean) / std          # broadcasts: (N,T) - (N,1)
print("normalized", normalized)
# Mask out rows with any NaN
valid = ~np.isnan(normalized).any(axis=1) # find NaN values
#if the row has it mark true, else false. then '~' flips T and F-> [F,T,F]->[T,F,T] 
print("valid", valid)
clean = normalized[valid]                 # fancy index → copy 
#clean = normalized[valid] is called fancy indexing because you're using an array of Boolean values to select elements.
print("clean", clean)

data [[ 1.  2.  3.  4.]
 [ 5. nan  7.  8.]
 [10. 20. 30. 40.]
 [nan  2.  4.  6.]]
mean [[ 2.5]
 [ nan]
 [25. ]
 [ nan]]
std [[ 1.11803399]
 [        nan]
 [11.18033989]
 [        nan]]
normalized [[-1.34164079 -0.4472136   0.4472136   1.34164079]
 [        nan         nan         nan         nan]
 [-1.34164079 -0.4472136   0.4472136   1.34164079]
 [        nan         nan         nan         nan]]
valid [ True False  True False]
clean [[-1.34164079 -0.4472136   0.4472136   1.34164079]
 [-1.34164079 -0.4472136   0.4472136   1.34164079]]


In [ ]:
arr=np.array([[1,2,3,4],[3,4,5,6]])
print(arr.shape)
print(arr.dtype)
print(arr.strides) #how many bytes to jump to reach the next element along each axis

(2, 4)
int64
(32, 8)
